<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>MovieVoltage - Watch Drama Movies</title>

  <!-- Flutterwave -->
  <script src="https://checkout.flutterwave.com/v3.js"></script>

  <style>
    body {
      margin: 0;
      font-family: 'Segoe UI', sans-serif;
      background-color: #121212;
      color: white;
      transition: 0.3s ease;
    }

    header {
      background-color: #1f1f1f;
      padding: 15px 20px;
      display: flex;
      flex-wrap: wrap;
      justify-content: space-between;
      align-items: center;
    }

    header h1 {
      color: #4caf50;
      margin: 0;
    }

    .btn {
      background-color: #4caf50;
      color: white;
      border: none;
      padding: 8px 15px;
      cursor: pointer;
      border-radius: 5px;
      font-weight: bold;
      margin: 5px;
    }

    .grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
      gap: 20px;
      padding: 20px;
    }

    .movie-card {
      background-color: #1e1e1e;
      border-radius: 10px;
      overflow: hidden;
      text-align: center;
      padding-bottom: 10px;
    }

    .movie-card img {
      width: 100%;
      height: 260px;
      object-fit: cover;
    }

    .movie-card h3 {
      margin: 10px 0 5px;
    }

    .location {
      font-size: 14px;
      color: #bbb;
      margin-bottom: 10px;
    }

    footer {
      text-align: center;
      padding: 15px;
      background-color: #1f1f1f;
      color: #aaa;
    }

    .light-mode {
      background-color: #ffffff;
      color: #000000;
    }

    .light-mode header,
    .light-mode footer {
      background-color: #eee;
      color: #000;
    }

    .light-mode .movie-card {
      background-color: #f5f5f5;
      color: #000;
    }

    .password-box {
      margin-top: 10px;
      display: none;
    }

    input[type="text"] {
      padding: 8px;
      border: none;
      border-radius: 4px;
      width: 80%;
      margin-bottom: 10px;
    }

    .search-bar {
      flex: 1;
      max-width: 300px;
      margin-top: 10px;
    }

    .search-bar input {
      width: 100%;
      padding: 8px 12px;
      border-radius: 5px;
      border: none;
    }
  </style>
</head>
<body>

  <header>
    <h1>🎬 MovieVoltage</h1>
    <div class="search-bar">
      <input type="text" placeholder="Search movies..." onkeyup="searchMovies(this.value)">
    </div>
    <button class="btn" onclick="toggleTheme()">Toggle Theme</button>
  </header>

  <section class="grid" id="movies">
    <div class="movie-card" data-title="Drama Movie 1">
      <img src="https://via.placeholder.com/200x260?text=Drama+1" alt="Drama Movie">
      <h3>Drama Movie 1</h3>
      <p class="location">Lagos, Nigeria</p>
      <button class="btn" onclick="payNow('Drama Movie 1', 'ABC123')">Pay ₦200</button>
      <div class="password-box" id="box-Drama Movie 1">
        <input type="text" readonly value="ABC123">
        <small>Use this password to watch the movie</small>
      </div>
    </div>

    <div class="movie-card" data-title="Drama Movie 2">
      <img src="https://via.placeholder.com/200x260?text=Drama+2" alt="Drama Movie">
      <h3>Drama Movie 2</h3>
      <p class="location">Abuja, Nigeria</p>
      <button class="btn" onclick="payNow('Drama Movie 2', 'XYZ789')">Pay ₦200</button>
      <div class="password-box" id="box-Drama Movie 2">
        <input type="text" readonly value="XYZ789">
        <small>Use this password to watch the movie</small>
      </div>
    </div>

    <!-- You can add more movies here by copying the same structure -->
  </section>

  <footer>
    &copy; 2025 Kenneth - MovieVoltage. All rights reserved.
  </footer>

  <script>
    function toggleTheme() {
      document.body.classList.toggle("light-mode");
    }

    function payNow(title, password) {
      FlutterwaveCheckout({
        public_key: "FLWPUBK-ebe1d9b4d2af10be6fca550404289dd9-X",
        tx_ref: "MOVIEVOL" + Date.now(),
        amount: 200,
        currency: "NGN",
        payment_options: "card, banktransfer",
        customer: {
          email: "user@example.com",
          name: "MovieVoltage Viewer"
        },
        callback: function (data) {
          if (data.status === "successful") {
            alert("Payment Successful! Your password will now appear.");
            document.getElementById('box-' + title).style.display = 'block';
          } else {
            alert("Payment failed or cancelled.");
          }
        },
        customizations: {
          title: title,
          description: "Access to " + title,
          logo: "https://via.placeholder.com/100x100?text=MV"
        }
      });
    }

    function searchMovies(query) {
      const cards = document.querySelectorAll('.movie-card');
      query = query.toLowerCase();
      cards.forEach(card => {
        const title = card.getAttribute('data-title').toLowerCase();
        card.style.display = title.includes(query) ? "block" : "none";
      });
    }
  </script>

</body>
</html>
